<?php

namespace ContainerLeXhbvI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_KeXosqEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.KeXosqE' shared service.
     *
     * @return \App\Controller\CallApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\HomeController::index()": the $callApiService argument is type-hinted with the non-existent class or interface: "App\\Controller\\CallApiService". Did you forget to add a use statement?');
    }
}
