<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGQErhwo\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGQErhwo/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerGQErhwo.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerGQErhwo\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerGQErhwo\App_KernelProdContainer([
    'container.build_hash' => 'GQErhwo',
    'container.build_id' => '9457d820',
    'container.build_time' => 1664627243,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGQErhwo');
