accueil:
   path: /
   controller: App\Controller\AccueilController::index

# a-propos:
#   path: /a-propos
#   controller: App\Controller\AproposController::index

# blog:
#    path: /auteur-du-blog
#    controller: App\Controller\AuteurController::index

# articles:
#   path: /articles
#   controller: App\Controller\ArticlesController::index

# post_item:
#     path: /article/fonctionnement-des-applications-symfony
#     controller: App\Controller\PostController::item

# contact:
#   path: /contact
#   controller: App\Controller\ContactController::index
