<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHUZixEu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHUZixEu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHUZixEu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHUZixEu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHUZixEu\App_KernelDevDebugContainer([
    'container.build_hash' => 'HUZixEu',
    'container.build_id' => '21ec5d0b',
    'container.build_time' => 1664968632,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHUZixEu');
