<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA6rYBeO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA6rYBeO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA6rYBeO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA6rYBeO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA6rYBeO\App_KernelDevDebugContainer([
    'container.build_hash' => 'A6rYBeO',
    'container.build_id' => '44e1a048',
    'container.build_time' => 1664715302,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA6rYBeO');
