<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'add_product' => [[], ['_controller' => 'App\\Controller\\ProductController::addProduct'], [], [['text', '/add-product']], [], [], []],
    'products' => [[], ['_controller' => 'App\\Controller\\ProductController::products'], [], [['text', '/products']], [], [], []],
    'product' => [['id'], ['_controller' => 'App\\Controller\\ProductController::product'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], [], []],
    'modify_product' => [['id'], ['_controller' => 'App\\Controller\\ProductController::modifyProduct'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/modify-product']], [], [], []],
    'delete_product' => [['id'], ['_controller' => 'App\\Controller\\ProductController::deleteProduct'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete-product']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/']], [], [], []],
];
