<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/']], [], [], []],
    'a-propos' => [[], ['_controller' => 'App\\Controller\\AproposController::index'], [], [['text', '/a-propos']], [], [], []],
    'blog' => [[], ['_controller' => 'App\\Controller\\AuteurController::index'], [], [['text', '/auteur-du-blog']], [], [], []],
    'articles' => [[], ['_controller' => 'App\\Controller\\ArticlesController::index'], [], [['text', '/articles']], [], [], []],
    'post_item' => [[], ['_controller' => 'App\\Controller\\PostController::item'], [], [['text', '/article/fonctionnement-des-applications-symfony']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], [], []],
];
